version: '2'
services:
  mariadb:
    image: mariadb:10.1
    container_name: mariadb7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=db_user
    volumes:
      - /var/www/docker/mariadb/:/var/lib/mysql
    restart: always
    ports:
     - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
    restart: always
    ports:
     - "8081:80"
  redishost:
    image: redis
    # command: redis-server --requirepass redispass
    container_name: php_redis2
    restart: always
    ports:
     - "6379:6379"
    volumes:
     - /var/www/docker/redis:/data
  php:
    image: mehrdadkhah/php7:latest
    container_name: php7
    environment:
        - DB_HOST=mariadb
        - DB_PASSWORD=123456
        - DB_DATABASE=docker_db
        - DB_USERNAME=db_user
        - REDIS_HOST=redishost
        # - REDIS_PASSWORD=redispass
        - REDIS_PORT=6379
        - APP_DEBUG=true
    volumes:
      - /var/www/docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    restart: always
    depends_on:
     - mariadb
     - redishost
    ports:
     - "9000:9000"
    volumes:
     - /var/www/html/:/var/www/html/
  nginx:
    image: nginx
    container_name: nginx_php7
    restart: always
    depends_on:
     - php
     - mariadb
    ports:
     - 8082:80
    volumes:
     - /var/www/html/:/var/www/html/
     - /var/www/docker/default.conf:/etc/nginx/conf.d/default.conf
     # - /var/www/docker/nginx.conf:/etc/nginx/nginx.conf
  rabbitmq:
    image: rabbitmq:3.6-management
    restart: always
    expose:
      - "4369"
      - "5671"
      - "5672"
      - "25672"
    ports:
      - 15672:15672